### ISSUE TITLE
[Suggestion] Tiers and Durability

### ISSUE THREAD

**Issue by BlackBeltPanda** [Falseee/Builder-s-Wand#11]
Would be great if there were multiple tiers of wands with varying durability, like in the mod. Wood, Stone, Gold, Iron, Diamond, etc.
Would be even greater if the different tiers had different amounts of blocks they could affect. =)

**Comment by Falseee** [comment]
Thank you for the feature request, i will add it maybe !

**Comment by Falseee** [comment]
@BlackBeltPanda 
In the new version (will be released soon) there are both features added.
You can add unlimited wands with all configuration (also durability).
