### ISSUE TITLE
New update of Lands renders Builders Wand unusable due to deprecated LandsIntegration API code

### ISSUE THREAD

**Issue by FourNineRugz** [Falseee/Builder-s-Wand#81]
[00:28:15 INFO]: [Lands] Nag author(s) of plugin BuildersWand. It uses the deprecated LandsIntegration of Lands: https://github.com/Angeschossen/LandsAPI/wiki/API-Update

**Comment by UtechtDustin** [comment]
Thanks for the info, i will check that in the evening.

**Comment by FourNineRugz** [comment]
Any update @UtechtDustin ? I would really love for my players to start using it again!

**Comment by UtechtDustin** [comment]
@FourNineRugz i'm on it, i wait for an answer from the Lands dev.

**Comment by UtechtDustin** [comment]
@FourNineRugz sorry for deleting your comment, i misclicked (there is no way to restore it).
I updated the plugin to the newest Lands Version.
