### ISSUE TITLE
[Enhancement] Please Add KingdomsX Land Claim Support

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Falseee/Builder-s-Wand#90]
I'd love to buy and use this plugin but before I do I need it to support KingdomsX land claims. Could you please add that? 

Plugin page: https://www.spigotmc.org/resources/kingdomsx.77670/
In order to download their plugin for free join their Discord: https://discord.gg/cKsSwtt
API Wiki: https://github.com/CryptoMorin/KingdomsX/wiki/API

Thank you!

**Comment by PiggiesGoSqueal** [comment]
Bump

**Comment by PiggiesGoSqueal** [comment]
Bump

**Comment by UtechtDustin** [comment]
As this is an premium Plugin and i don't own that plugin, i'm not able to implement/test it.
